USE [master]
GO

/****** Object:  Database [ChatDB]    Script Date: 13.01.2017 17:46:02 ******/
CREATE DATABASE [ChatDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChatDB', FILENAME = N'D:\INSTAL\MSSQL\DATA\ChatDB.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ChatDB_log', FILENAME = N'D:\INSTAL\MSSQL\DATA\ChatDB_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ChatDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChatDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChatDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChatDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChatDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChatDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChatDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChatDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChatDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChatDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChatDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChatDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChatDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChatDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChatDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChatDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChatDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ChatDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChatDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChatDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChatDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChatDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChatDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ChatDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChatDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ChatDB] SET  MULTI_USER 
GO

ALTER DATABASE [ChatDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChatDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChatDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChatDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ChatDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChatDB] SET  READ_WRITE 
GO




USE [ChatDB]
GO

/****** Object:  Table [dbo].[Users]    Script Date: 13.01.2017 17:43:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Users](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [Chats](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Chats] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

CREATE TABLE [Messages](
	[Id] [uniqueidentifier] NOT NULL,
	[ChatId] [uniqueidentifier] NOT NULL,
	[SendDateTime] [datetime] NOT NULL,
	[Content] [nvarchar](max) NULL,
 CONSTRAINT [PK_dbo.Messages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
